### ISSUE TITLE
Technical Design

### ISSUE THREAD

**Issue by conneralegre** [kodaxx/bwa-u4-feature-request#2]
The technical design makes sense - we use a built in event listener `onKeyPress` and bind that to an event handler. This is an easy implementation for a big bonus to our users. I would recommend adding more code examples to help further solidify this idea.

**Comment by kodaxx** [comment]
Will do next time. It was my understanding that this is a type of document possibly written by non coders, so I attempted to challenge myself to explain the code rather than just write it. But it makes sense, anything to help the engineers, including code examples
